sonar.projectKey=your-org_medical-telegram-warehouse
sonar.projectName=Medical Telegram Warehouse
sonar.projectVersion=1.0.0

sonar.sources=src/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=pytest-report.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/data/**,**/logs/**
sonar.test.exclusions=**/__pycache__/**,**/*.pyc

sonar.language=py
sonar.python.version=3.10

sonar.organization=your-org
sonar.host.url=https://sonarcloud.io